# Generated by Django 3.2.15 on 2022-08-10 17:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('province', models.CharField(choices=[('Assam Province', 'Assam Province'), ('Bihar Province', 'Bihar Province'), ('Bombay Province', 'Bombay Province'), ('Punjab Province', 'Punjab Province'), ('Orissa Province', 'Orissa Province'), ('United Province', 'United Province'), ('Rajputana Province', 'Rajputana Province')], max_length=30)),
                ('district', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('Consultation', 'Consultation'), ('Investigation', 'Investigation'), ('Procedures', 'Procedures'), ('Clinics', 'Clinics'), ('Rehabilitation ', 'Rehabilitation '), ('Counseling', 'Counseling')], max_length=30)),
                ('hospital_code', models.IntegerField(default=0)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
